### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/sinatra-video-review-authentication#2]
_Suggested Summary_
- This lesson starts with an overview of how to build a Sinatra application from scratch and then focuses on authentication and how to implement it. It finishes with a quick discussion on when to _render_ vs. _redirect_.

_Suggested Objectives_
- Create a Sinatra application from scratch; setting up the necessary directories / files, requirements, mounting controllers, installing necessary gems, etc.
- Understand why it makes sense to place _require ‘sinatra/activerecord/rake’_ in the _Rakefile_ instead of the _environment_ file. 
- Enable sessions so that you can utilize cookies and the _session_ hash.
- Define _session hijacking_ and why it is important to not place sensitive information in the cookies generated by your site. 
- Describe what question _authentication_ is really seeking to answer: “Is the user who they claim to be?”
- Remember that methods which are utilized across numerous views / controllers should be placed in the _helpers_ block, within the _ApplicationController_.
- Understand that one reason helper methods are so valuable is because they make your program more _open to extension_.
- Explain what the _!!_ operand does and why it’s useful. 
- Utilize _if statement assignment_ to condense and simplify code in conditional statements.
- Use the _has_secure_password_ macro and understand what it actually _does_ (adds methods to the class it is included in).
- See what _bcrypt_ does to a password when it is saved into the _password_digest_ column of a database table.
- Use _authenticate_ to check user entry against passwords saved in a database.
- Understand when it is appropriate to _render_ a view and when it is appropriate to _redirect_ to a new route (and how this is based upon the stateless characteristic of HTTP).

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary and Objectives
