### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/sinatra-video-review-authentication#3]
Summary:
This video first walks through the process of setting up a Sinatra application from scratch, including creating the file structure and necessary files, adding the needed gems, enabling sessions, and setting up the database connection. Once the application structure is set up, the video covers how to create a secure user registration and login system. Finally, we see how to use object relationships to ensure that only the user who owns a specific piece of content can edit that content.

Objectives:
Create a Sinatra application from scratch
Create a secure registration and login system using the BCrypt gem and has_secure_password macro
Use sessions to securely persist information across pages in an application
Use controller helper methods and memoization to create code that is efficient, semantic and easy to extend
Use object relationships to confine the ability to edit content to the content's owner

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary and Objectives
