### ISSUE TITLE
Broken youtube links

### ISSUE THREAD

**Issue by YoshiMejia** [learn-co-curriculum/sinatra-video-review-authentication#6]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/1880/pages/sinatra-video-review-authentication?module_item_id=259345

## What should be changed?

This, and nearly all the other video review lessons in this phase, have broken youtube links

**Comment by ihollander** [comment]
Hi @slothabel - thanks for flagging this issue. This video along with the others were recorded by an instructor who is no longer with Flatiron and have subsequently been removed from YouTube so unfortunately we no longer have access to them. We've removed these videos in Canvas so future students won't see the broken video links.
